version: '3.8'

services:
  telegram:
    build: .
    container_name: bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ANTHROPISM_API_KEY=${ANTHROPISM_API_KEY}
    restart: always